// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGkhOP5Jkm89i0NwxUIn-OdHTdLUz1nHQ',
    appId: '1:964118470426:web:078295984d7f7a28df56a3',
    messagingSenderId: '964118470426',
    projectId: 'arroz-17a52',
    authDomain: 'arroz-17a52.firebaseapp.com',
    storageBucket: 'arroz-17a52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL1ljqVqOUuFKgoREGgcvqYiy1Q3ThKd4',
    appId: '1:964118470426:android:c52846e252100bccdf56a3',
    messagingSenderId: '964118470426',
    projectId: 'arroz-17a52',
    storageBucket: 'arroz-17a52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6s6HCIkjoIOsj55uFCoV-ESo9mfmcf_0',
    appId: '1:964118470426:ios:c92f0ee8c339db97df56a3',
    messagingSenderId: '964118470426',
    projectId: 'arroz-17a52',
    storageBucket: 'arroz-17a52.firebasestorage.app',
    iosBundleId: 'com.example.arrozApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6s6HCIkjoIOsj55uFCoV-ESo9mfmcf_0',
    appId: '1:964118470426:ios:c92f0ee8c339db97df56a3',
    messagingSenderId: '964118470426',
    projectId: 'arroz-17a52',
    storageBucket: 'arroz-17a52.firebasestorage.app',
    iosBundleId: 'com.example.arrozApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGkhOP5Jkm89i0NwxUIn-OdHTdLUz1nHQ',
    appId: '1:964118470426:web:e73e0dc2db81c872df56a3',
    messagingSenderId: '964118470426',
    projectId: 'arroz-17a52',
    authDomain: 'arroz-17a52.firebaseapp.com',
    storageBucket: 'arroz-17a52.firebasestorage.app',
  );

}